#!/usr/bin/env bash
# maintainer lxgr <lxgr@protonmail.com>

editor=nano
showPKGBUILD=1
sudoreset=1
. /etc/buildaur/buildaur.conf
black=($(cat /usr/share/buildaur/blacklist))
bold=$(tput bold)
red=$(tput setaf 1)
grey=$(tput setaf 7)
normal=$(tput sgr0)

options(){
	installindex=i
	if [[ $(echo $1 | egrep n) != "" ]]
	then
		ask=--noconfirm
	fi
	if [[ $(echo $1 | egrep spgp) != "" ]]
	then
		pgp=--skippgpcheck
	fi
	if [[ $(echo $1 | egrep c) != "" ]]
	then
		buildchroot=yes
		if [[ $(uname -m) = armv7l ]]
		then
			echo ":: ${bold}Warning:${normal} You may run into some issues using chroots on ALARM!"
		fi
	fi
	if [[ $(echo $1 | egrep di) != "" ]]
	then
		installindex=""
	fi
}

netcheck(){
	inet=1
	if [[ $net != true ]]
	then
		if [[ $(ping -c 1 google.de >/dev/null 2>/dev/null ; echo $?) != 0 ]]
		then
			if [[ $1 = -x ]]
			then
				inet=0
			else
				echo ":: ${red}${bold}ERROR:${normal} Network is not reachable!"
				exit 1
			fi
		fi
		net=true
  fi
}

info(){
	netcheck -x
	pkgnames=($@)
	if [[ $all = true ]] && [[ $inet = 0 ]]
	then
		echo 3
		res=$(cat /usr/share/buildaur/res)
	else
		if [[ $inet = 0 ]]
		then
			if [[ $notext != 1 ]]
			then
			 echo -e ":: ${red}${bold}ERROR:${normal} Network is not reachable!"
			fi
			exit 1
		fi
		if [[ $notext != 1 ]]
		then
			if [[ $all = true ]]
			then
				echo -e ":: Syncing database..."
			else
				echo ":: Qetting package infos..."
			fi
		fi
		res="https://aur.archlinux.org/rpc/?v=5&type=multiinfo"
		counter=0
		while [[ $counter -lt ${#pkgnames[*]} ]]
		do
			res=${res}"&arg[]="${pkgnames[$counter]}
			((counter++))
		done
		res=$(curl -s $res)
		if [[ $all = true ]]
		then
			sudo sh -c "echo '$res' > /usr/share/buildaur/res"
		fi
	fi
	resultcount=$(echo $res | cut -d'"' -f9 | sed -e 's/://g' | sed -e 's/,//g')
	counter=0
	if [[ $notext != 1 ]]
	then
		echo -e ":: Giving out package infos..."
	fi
	while [[ $counter -lt $resultcount ]]
	do
		cutted=$(echo $res | cut -d{ -f$(expr $counter + 3))
		name=$(echo $cutted | cut -d'"' -f6)
		ver=$(pacman -Qqi $name 2>/dev/null | xargs 2>/dev/null | awk {'print $6'})
		remoteinfo=$(echo $cutted | cut -d'"' -f20)
		if [[ $name = "" ]] || [[ $ver = "" ]]
		then
			ver="--- "
		fi
		if [[ $q = 1 ]]
		then
			echo $name
		else
			echo "  "$name $(echo $cutted | cut -d'"' -f16) "(local: $ver)"
			if [[ $remoteinfo = "" ]]
			then
				echo "     ${bold}Warning:${normal} AUR does not provide information about this package!"
			else
				echo "     "$remoteinfo
			fi
		fi
		aurpacs[$counter]=$name
		((counter++))
	done
	if [[ $only = aur ]]
	then
		exit
	fi
	localpacs=($(echo ${aurpacs[@]} $@ | tr ' ' '\n' | sort | uniq -u))
	counter=0
	for pac in ${localpacs[@]}
	do
		aspinfo=$(asp show $pac 2>/dev/null)
		pkgver=0
		# if [[ $q = 1 ]]
		# then
		# 	if [[ $(pacman -Qi $pac 2>/dev/null) != "" ]]
		# 	then
		# 		echo $pac
		# 	fi
		if [[ $aspinfo = "" ]]
		then
			if [[ $(pacman -Qi $pac 2>/dev/null) != "" ]]
			then
				if [[ $q = 1 ]]
				then
					echo $pac
				else
					pkgver=$(pacman -Qi $pac 2>/dev/null | xargs | awk {'print $6'})
					echo "  $pac-$ver is not installed from ASP!"
					echo "     ${bold}Warning:${normal} AUR does not provide information about this package!"
				fi
			fi
		else
			if [[ $q = 1 ]]
			then
				echo $pac
			else
				aspout=$(echo "$aspinfo" | egrep pkgver | head -1)
				aspoutrel=$(echo "$aspinfo" | egrep pkgrel | head -1)
				aspoutdesc=$(echo "$aspinfo" | egrep pkgdesc | head -1)
				declare $aspout
				declare $aspoutrel
				declare "$aspoutdesc"
				ver=$(pacman -Qqi $pac | xargs 2>/dev/null | awk {'print $6'})
				echo "  $pac $pkgver-$pkgrel (local: $ver)"
				echo "     $(echo $pkgdesc | sed 's/"//g')"
			fi
		fi
		((count++))
	done
}

search(){
	netcheck
	while [[ $# -gt 1 ]]
	do
		key=$2
		echo ":: Checking AUR packages..."
		res=$(curl -s 'https://aur.archlinux.org/rpc/?v=5&type=search&arg='$key'')
		resultcount=$(echo $res | cut -d'"' -f9 | sed -e 's/://g' | sed -e 's/,//g')
		echo "  $resultcount packages found"
  	echo ":: Giving out package infos..."
		counter=0
		while [[ $counter -lt $resultcount ]]
		do
			cutted=$(echo $res | cut -d{ -f$(expr $counter + 3))
			name=$(echo $cutted | cut -d'"' -f6)
			ver=$(pacman -Q $name 2>/dev/null | cut -d" " -f2 | xargs)
			remoteinfo=$(echo $cutted | cut -d'"' -f20)
			if [[ $name = "" ]] || [[ $ver = "" ]]
			then
			ver="--- "
			fi
			echo "  "$name $(echo $cutted | cut -d'"' -f16) "(local: $ver)"
			if [[ $remoteinfo = "" ]]
			then
				echo "     ${bold}Warning:${normal} AUR does not provide information about this package!"
			else
				echo "     "$remoteinfo
			fi
			counter=$(expr $counter + 1)
		done
		shift
	done
}

depts(){
	. ./PKGBUILD
	depends=($(echo -e ${depends[@]} ${makedepends[@]} | sed 's/ /\n/g'| uniq))
	aurdeps=()
	mayaurdeps=()
	depcount=0
	depmaxcount=${#depends[*]}
	echo ":: Checking for dependecies..."
	echo "  ($depmaxcount) Packages: ${depends[@]}"
	echo ":: Checking for unresolved dependecies..."
	for pac in ${depends[@]}
	do
		if [[ $(pacman -Si $pac 2>/dev/null) = "" ]] && [[ $(pacman -Qi $pac 2>/dev/null) = "" ]]
		then
			mayaurdeps=(${maybeaurdeps[@]} $pac)
		fi
	done
	aurdeps=(${mayaurdeps[@]})
	notext=1
	q=1
	aurdeps=($(info ${aurdeps[@]}))
	echo "  (${#aurdeps[*]}) Packages: ${aurdeps[@]}"
	if [[ ${aurdeps[@]} != "" ]]
	then
		echo ":: Installing them..."
		echo
		install ${aurdeps[@]}
		echo
	fi
}

install(){
	if [[ $@ = "" ]]
	then
		echo " Nothing to do"
	else
		netcheck
		echo ":: Running prerunhooks..."
		prerun
		installcount=1
		preinst $@
		echo ":: Running postrunhooks..."
		postrun
	fi
}

preinst(){
	echo ":: Checking packages..."
	installpac=()
	niceinstallpac=()
	while [[ $# -gt 0 ]]
	do
		key=$1
		if [[ $mode != asp ]] && [[ $mode != url ]]
		then
			ver=$(pacman -Qqi $key 2>/dev/null| xargs 2>/dev/null | awk {'print $6'})
			res=$(curl -s 'https://aur.archlinux.org/rpc/?v=5&type=multiinfo&arg[]='$key'')
			remotever=$(echo $res | cut -d'"' -f26)
			if [[ $(echo $res | cut -d'"' -f9) = ":0," ]]
			then
				echo "${red}${bold}ERROR:${normal} $key ist not in the AUR!"
				exit 1
			fi
			if [[ $ver = "" ]]
			then
				printf ""
			elif [[ $ver = $remotever ]]
			then
				echo "${bold}Warning:${normal} $key-$ver is allready on $remotever -- reinstalling"
			elif [[ $(echo -e "$ver\n$remotever" | sort -V | xargs | awk {'print $1'}) = $ver ]]
			then
				echo "Info: $key-$ver will be updated to $remotever!"
			else
				echo "${bold}Warning:${normal} $key-$ver is higher than AUR $remotever!"
			fi
			if [[ $(echo $res | cut -d'"' -f41) != :null, ]]
			then
				echo  "${bold}Warning:${normal} $key is flagged out of date!"
			fi
		elif [[ $mode = asp ]]
		then
			aspout=$(echo "$(asp show $key 2>/dev/null)" | egrep pkgver | head -1)
			aspoutrel=$(echo "$(asp show $key 2>/dev/null)" | egrep pkgrel | head -1)
			ver=$(pacman -Qqi $key 2>/dev/null| xargs 2>/dev/null | awk {'print $6'})
			pkgver=0
		 	if [[ $aspout = "" ]]
			then
				echo "${red}${bold}ERROR:${normal} $key ist not on ASP!"
				exit 1
			fi
			declare $aspout
			declare $aspoutrel
			remotever=$pkgver-$pkgrel
			if [[ $ver = "" ]]
			then
				printf ""
			elif [[ $ver = $pkgver-$pkgrel ]]
			then
				echo "${bold}Warning:${normal} $key-$ver is allready on $pkgver-$pkgrel -- reinstalling"
			elif [[ $(echo -e "$ver\n$pkgver-$pkgrel" | sort -V | xargs | awk {'print $1'}) = $ver ]]
			then
				echo "Info: $key-$ver will be updated to $pkgver-$pkgrel!"
			else
				echo "${bold}Warning:${normal} $key-$ver is higher than ASP $pkgver-$pkgrel!"
			fi
		fi
		installpac=(${installpac[@]} $key)
		niceinstallpac=(${niceinstallpac[@]} $key-$remotever)
		shift
	done
	echo ""
	echo "Packages (${#installpac[*]}): ${niceinstallpac[@]}"
	echo ""
	if [[ $ask = "--noconfirm" ]]
	then
		ans=y
	else
		echo ":: Continnue installation? [Y/n]"
		read ans
	fi
	if [[ $ans == y ]] || [[ $ans == "" ]]
	then
		realinst ${installpac[@]}
	fi
}

realinst(){
	sudo pacman -Sy
	while [[ $# -gt 0 ]]
	do
		echo ""
		if [[ $mode = asp ]] || [[ $mode = url ]]
		then
			echo "($installcount/$(expr $# + $installcount - 1)) Installing ${bold}$1${normal} ..."
		else
			echo "($installcount/$(expr $# + $installcount - 1)) Installing ${bold}$1-$remotever${normal} ..."
		fi
		mkdir -p ~/.cache/buildaur/build
		cd ~/.cache/buildaur/build
		if [[ $mode = url ]]
		then
			find ./urlbuild/buildaur.lock >/dev/null 2>/dev/null
			if [[ $? = 0 ]]
			then
				echo ":: ${red}${bold}ERROR:${normal} Buildaur is currendly working in this directory! Finnish the process or remove $(pwd)/urlbuild/buildaur.lock!"
				exit 1
			fi
		else
			find ./$1/buildaur.lock >/dev/null 2>/dev/null
			if [[ $? = 0 ]]
			then
				echo ":: ${red}${bold}ERROR:${normal} Buildaur is currendly working in this directory! Finnish the process or remove $(pwd)/$1/buildaur.lock!"
				exit 1
			fi
		fi
		rm -rf  ~/.cache/buildaur/build/$1
		rm -rf  ~/.cache/buildaur/build/urlbuild
		if [[ $mode = asp ]]
		then
			echo ":: Exporting package..."
			asp export $1 2>/dev/null
			cd ~/.cache/buildaur/build/$1
			if [[ $? != 0 ]]
			then
				echo ":: ${red}${bold}ERROR:${normal} $1 not found!"
				exit 2
			fi
		else
			echo ":: Clonig git repository..."
			if [[ $mode = url ]]
			then
				git clone $1 ~/.cache/buildaur/build/urlbuild
				cd ~/.cache/buildaur/build/urlbuild
			else
				git clone https://aur.archlinux.org/$1.git ~/.cache/buildaur/build/$1
				cd ~/.cache/buildaur/build/$1
			fi
		fi
		touch ./buildaur.lock
		if [[ $showPKGBUILD = 1 ]]
		then
			echo ":: Printing out PKGBUILD...${grey}"
			echo ""
			cat ./PKGBUILD | sed 's/^/  /g'
			echo "$normal"
		fi
		if [[ $ask = "--noconfirm" ]]
		then
			ans=n
		else
			echo ":: Edit the PKGBUILD? [y/N]"
			read ans
		fi
		if [[ $ans == n ]] || [[ $ans == "" ]]
		then
			echo ":: Going on..."
		else
			$editor ./PKGBUILD
		fi
		echo ":: Running prehooks..."
		if [[ $sudoreset = 1 ]]
		then
			sudo -k
		fi
		prehooks
		depts
		if [[ $mode = url ]]
		then
			cd ~/.cache/buildaur/build/urlbuild
		else
			cd ~/.cache/buildaur/build/$1
		fi
		if [[ $buildchroot = yes ]]
		then
			if [[ $CHROOT = "" ]]
			then
				echo ":: ${red}${bold}ERROR:${normal}: CHROOT variable is not defined! Use '--make-chroot' to create a chroot first"
				exit 1
			fi
			echo ":: Updating chrootpackages..."
			arch-nspawn $CHROOT/root pacman -Syu $ask
			echo ":: Making and installing the package..."
			makechrootpkg -c -r $CHROOT -- -sf $ask $pgp
			. ./PKGBUILD
			if [[ $installindex = i ]]
			then
				sudo pacman -U $ask ./${pkgname}-${pkgver}-${pkgrel}-${arch}.pkg.tar.xz
			fi
		else
			echo ":: Making and installing the package..."
			makepkg -s${installindex}f $ask $pgp
		fi
		if [[ $? = 0 ]]
		then
			echo ":: Running posthooks..."
			posthooks
			if [[ $installindex = "" ]]
			then
				echo ":: Info: Succesfully created package in $(pwd)!"
			else
				echo ":: Installation finished!"
			fi
		else
			echo ":: ${red}${bold}ERROR:${normal} Package installation FAILED!"
			errorcount=$(expr $errorcount + 1)
		fi
		rm ./buildaur.lock
		shift
		installcount=$(expr $installcount + 1)
	done
}

update(){
	netcheck
	pkgnames=($(pacman -Qqm))
	res="https://aur.archlinux.org/rpc/?v=5&type=multiinfo"
	counter=0
	while [[ $counter -lt ${#pkgnames[*]} ]]
	do
		res=${res}"&arg[]="${pkgnames[$counter]}
		((counter++))
	done
	echo ":: Downloading packagelist..."
	res=$(curl -s $res)
	sudo sh -c "echo '$res' > /usr/share/buildaur/res"
	resultcount=$(echo $res | cut -d'"' -f9 | sed -e 's/://g' | sed -e 's/,//g')
	willinst=()
	errorcount=0
	counter=0
	count=1
	echo ":: Checking installed AUR packages..."
	echo "  $resultcount packages are curently installed from the AUR!"
	echo ":: Checking for outdated packages..."
	while [[ $counter -lt $resultcount ]]
	do
		cutted=$(echo $res | cut -d{ -f$(expr $counter + 3))
	  name=$(echo $cutted | cut -d'"' -f6)
	  ver=$(pacman -Qqi $name | xargs 2>/dev/null | awk {'print $6'})
		remotever=$(echo $cutted | cut -d'"' -f16)
	  if [[ $name = "" ]] || [[ $ver = "" ]]
	  then
	  ver="--- "
	  fi
		if [[ $(echo ${black[*]} | sed -e 's/ /\n/g'| egrep -xE $name) = "$name" ]]
		then
			echo "($count/$resultcount) $name-$ver is out of date! $remotever is available! But it's on the blacklist and will not be updated!"
		elif [[ $remotever = "$ver" ]]
		then
			echo "($count/$resultcount) $name-$ver is up to date"
		else
			if [[ $(echo -e "$ver\n$remotever" | sort -V | xargs | awk {'print $1'}) = $ver ]]
			then
				echo "($count/$resultcount) $name-$ver is out of date! $remotever is available!"
			else
				echo "($count/$resultcount) ${bold}Warning:${normal} $name-$ver is higher than AUR $remotever!"
			fi
			if [[ $ask = "--noconfirm" ]]
			then
				ans=y
			else
				echo ":: Should it be updated? [Y/n]"
				read ans
			fi
			if [[ $ans == y ]] || [[ $ans == "" ]]
			then
				willinst=(${willinst[@]} $name)
			fi
		fi
		aurpacs[$count]=$name
		((count++))
    ((counter++))
	done
	echo
	echo ":: Searching non AUR packages..."
	localpacs=($(echo ${aurpacs[@]} $(pacman -Qqm) | tr ' ' '\n' | sort | uniq -u))
	echo "  ${#localpacs[*]} packages are not installed from any repository"
	count=1
	willinstasp=()
	echo ":: Listing them..."
	for pac in ${localpacs[@]}
	do
		aspinfo=$(asp show $pac 2>/dev/null)
		pkgver=0
		if [[ $aspinfo = "" ]]
		then
			pkgver=$(pacman -Qqi $pac | xargs 2>/dev/null | awk {'print $6'})
			echo "($count/${#localpacs[*]}) $pac-$ver is not installed from ASP!"
		else
			aspout=$(echo "$aspinfo" | egrep pkgver | head -1)
			aspoutrel=$(echo "$aspinfo" | egrep pkgrel | head -1)
			declare $aspout
			declare $aspoutrel
			ver=$(pacman -Qqi $pac | xargs 2>/dev/null | awk {'print $6'})
			if [[ $(echo ${black[*]} | sed -e 's/ /\n/g'| egrep -xE $pac) = "$pac" ]]
			then
				echo "($count/${#localpacs[*]})) $pac-$pkgver-$pkgrel is out of date! $pkgver-$pkgrel is available! But it's on the blacklist and will not be updated!"
			elif [[ $pkgver-$pkgrel = "$ver" ]]
			then
				echo "($count/${#localpacs[*]}) $pac-$ver is up to date"
			else
				if [[ $(echo -e "$ver\n$pkgver-$pkgrel" | sort -V | xargs | awk {'print $1'}) = $ver ]]
				then
					echo "($count/${#localpacs[*]}) $pac-$ver is out of date! $pkgver-$pkgrel is available!"
				else
					echo "($count/${#localpacs[*]}) ${bold}Warning:${normal} $pac-$ver is higher than ASP $pkgver-$pkgrel!"
				fi
				if [[ $ask = "--noconfirm" ]]
				then
					ans=y
				else
					echo ":: Should it be updated? [Y/n]"
					read ans
				fi
				if [[ $ans == y ]] || [[ $ans == "" ]]
				then
					willinstasp=(${willinstasp[@]} $pac)
				fi
			fi
		fi
		((count++))
	done
	if [[ ${willinst[@]} != "" ]]
	then
		echo ""
		install ${willinst[@]}
	fi
	if [[ ${willinstasp[@]} != "" ]]
	then
		mode=asp
		install ${willinstasp[@]}
	fi
	if [[ ${willinstasp[@]} = "" ]] ; [[ ${willinst[@]} = "" ]]
	then
		echo " Nothing to do"
	fi
	if [[ $errorcount = 0 ]]
	then
		echo " No errors accured"
	else
		echo " $errorcount error(s) accured!"
	fi
}

prehooks(){
	prehooks=($(ls /etc/buildaur/prehooks))
	hookcount=0
	while [[ $hookcount -lt ${#prehooks[*]} ]]
	do
		echo " ${prehooks[$hookcount]}..."
		/etc/buildaur/prehooks/${prehooks[$hookcount]} -u
		hookcount=$(expr $hookcount + 1)
	done
}

posthooks(){
	posthooks=($(ls /etc/buildaur/posthooks))
	hookcount=0
	while [[ $hookcount -lt ${#posthooks[*]} ]]
	do
		echo " ${posthooks[$hookcount]}..."
		/etc/buildaur/posthooks/${posthooks[$hookcount]} -u
		hookcount=$(expr $hookcount + 1)
	done
}

prerun(){
	prerunhooks=($(ls /etc/buildaur/prerunhooks))
	hookcount=0
	while [[ $hookcount -lt ${#prerunhooks[*]} ]]
	do
		echo " ${prerunhooks[$hookcount]}..."
		/etc/buildaur/prerunhooks/${prerunhooks[$hookcount]} -u
		hookcount=$(expr $hookcount + 1)
	done
}

postrun(){
	postrunhooks=($(ls /etc/buildaur/postrunhooks))
	hookcount=0
	while [[ $hookcount -lt ${#prerunhooks[*]} ]]
	do
		echo " ${postrunhooks[$hookcount]}..."
		/etc/buildaur/postrunhooks/${postrunhooks[$hookcount]} -u
		hookcount=$(expr $hookcount + 1)
	done
}

listhooks(){
	echo "Prehooks:"
	prehooks=($(ls /etc/buildaur/prehooks))
	hookcount=0
	while [[ $hookcount -lt ${#prehooks[*]} ]]
	do
		. /etc/buildaur/prehooks/${prehooks[$hookcount]}
		echo " ${prehooks[$hookcount]}"
		echo "  $desc"
		hookcount=$(expr $hookcount + 1)
	done
	echo "Posthooks:"
	posthooks=($(ls /etc/buildaur/posthooks))
	hookcount=0
	while [[ $hookcount -lt ${#posthooks[*]} ]]
	do
		. /etc/buildaur/posthooks/${posthooks[$hookcount]}
		echo " ${posthooks[$hookcount]}"
		echo "  $desc"
		hookcount=$(expr $hookcount + 1)
	done
	echo "Prerunhooks:"
	prerunhooks=($(ls /etc/buildaur/prerunhooks))
	hookcount=0
	while [[ $hookcount -lt ${#prerunhooks[*]} ]]
	do
		. /etc/buildaur/prerunhooks/${prerunhooks[$hookcount]}
		echo " ${prerunhooks[$hookcount]}"
		echo "  $desc"
		hookcount=$(expr $hookcount + 1)
	done
	echo "Postrunhooks:"
	postrunhooks=($(ls /etc/buildaur/postrunhooks))
	hookcount=0
	while [[ $hookcount -lt ${#postrunhooks[*]} ]]
	do
		. /etc/buildaur/postrunhooks/${postrunhooks[$hookcount]}
		echo " ${postrunhooks[$hookcount]}"
		echo "  $desc"
		hookcount=$(expr $hookcount + 1)
	done
	echo "Deactivated hooks:"
	hooks=($(ls /etc/buildaur/hooks))
	hookcount=0
	while [[ $hookcount -lt ${#hooks[*]} ]]
	do
		. /etc/buildaur/hooks/${hooks[$hookcount]}
		echo " ${hooks[$hookcount]}"
		echo "  $desc"
		hookcount=$(expr $hookcount + 1)
	done
}

activate(){
	hookcount=$#
	while [[ $hookcount -gt 0 ]]
	do
		. /etc/buildaur/hooks/$1 2>/dev/null
		sudo mv /etc/buildaur/hooks/$1 /etc/buildaur/${type}hooks/ 2>/dev/null
		if [[ $? = 0 ]]
		then
			echo ":: Activated $1!"
		else
			echo ":: ${red}${bold}ERROR:${normal} $1 is not available!"
			exit 1
		fi
		hookcount=$(expr $hookcount - 1)
		shift
	done
}

deactivate(){
	hookcount=$#
	while [[ $hookcount -gt 0 ]]
	do
		. /etc/buildaur/prehooks/$1 2>/dev/null
		. /etc/buildaur/posthooks/$1 2>/dev/null
		. /etc/buildaur/prerunhooks/$1 2>/dev/null
		. /etc/buildaur/postrunhooks/$1 2>/dev/null
		sudo mv /etc/buildaur/${type}hooks/$1 /etc/buildaur/hooks/ 2>/dev/null
		if [[ $? = 0 ]]
		then
			echo ":: Deactivated $1!"
		else
			echo ":: ${red}${bold}ERROR:${normal} is not available!"
			exit 1
		fi
		hookcount=$(expr $hookcount - 1)
		shift
	done
}

hookhelp(){
	echo "Help-dialog for hooks"
	echo ""
	echo "  Hooks are skripts that run before and after the packagebuild."
	echo "  They are made to for example modify the PKGBUILD"
	echo "  All hooks are stored in /etc/buildaur/hooks"
	echo "  In /etc/buildaur/prehooks are the hooks stored wich run before the packagebuild"
	echo "  and in /etc/buildaur/posthooks those wich run after the packagebuild."
	echo "  A hook always contains a 'type' (pre oder post) and a 'desc' variable."
	echo "  It also contains an if-function wich contains the modifications for the PKGBUILD and so on"
	echo "  See /etc/buildaur/prehooks/1-arm-archfix as an example."
	echo ""
	echo "   Hookoptions:"
	echo "      --listhooks       : Lists all available and installed hooks"
	echo "      --hook-activate   : Activates a hook"
	echo "      --hook-deactivate : Deactivates a hook"
}

help(){
	echo "buildaur - An AUR helper"
	echo "Usage: $0 <option> <string>"
	echo "   General options:"
	echo "      -S                : Installs a package"
	echo "      -R                : Removes a package"
	echo "      -Q                : Lists installed packages or searches for ones in the AUR"
	echo "      -Qs               : Search the AUR"
	echo "      -Syu              : Updates all AUR packages"
	echo "      -url              : Installs a package from a given git-repository"
	echo "      -asp              : Builds a package from source using asp (usefull for archlinux arm)"
	echo "      --clear           : Cleanes build dir"
	echo "      -v|--version      : Displays version of this program"
	echo "      -l|--license      : Displays license of this program"
	echo "      --make-chroot     : Creates a chroot dir which can be used for building packages"
	echo ""
	echo "   Additional options for -S,-R,-Syu,-asp:"
	echo "      n                 : Doesn't ask questions"
	echo "      spgp              : Skips pgp checks of sourcecode"
	echo "      c                 : Builds the package in a clean chroot (you may run into some problems using this on archlinux arm!)"
	echo "      di                : Just builds the package"
	echo ""
	echo "   Hookoptions:"
	echo "      --listhooks       : Lists all available and installed hooks"
	echo "      --hook-activate   : Activates a hook"
  echo "      --hook-deactivate : Deactivates a hook"
	echo ""
	echo "   Help options:"
	echo "      -h|--help         : Displays this help-dialog"
	echo "      --help-hooks      : Displays help-dialog for hooks"
}

case $1 in
	-S | -Sn* | -Sspgp* | -Sc* | -Sdi* )
		options $@
		shift
		install $@
		exit 0
	;;
	-url*)
		options $@
		shift
		mode=url
		install $@
		exit 0
	;;
	-asp*)
		options $@
		shift
		mode=asp
		install $@
		exit 0
	;;
	-Q)
		shift
		if [[ $1 = "" ]]
		then
			echo ":: Checking installed AUR packages..."
			echo "  $(pacman -Qqm | wc -l) packages are curently installed from the AUR!"
			all=true
			info $(pacman -Qqm)
		else
			info $@
		fi
		exit 0
	;;
	-Qq)
		shift
		q=1
		if [[ $1 = "" ]]
		then
			echo ":: Checking installed AUR packages..."
			echo "  $(pacman -Qqm | wc -l) packages are curently installed from the AUR!"
			all=true
			info $(pacman -Qqm)
		else
			info $@
		fi
		exit 0
	;;
	-Qs)
		if [[ $2 = "" ]]
		then
			echo ":: ${red}${bold}ERROR:${normal} No search subject given!"
			exit 2
		else
			search $@
		fi
		exit 0
	;;
	-R)
		sudo pacman $@
		exit 0
	;;
	-Rn)
		sudo pacman --noconfirm $@
		exit 0
	;;
	-Syu*)
		options $@
		update
		exit 0
	;;
	--help | -h)
		help
		exit 0
	;;
	-v | --version)
		pacman -Q buildaur | cut -d" " -f2 | xargs
		exit 0
	;;
	-l | --license)
		less /usr/share/licenses/buildaur/LICENSE
		exit 0
	;;
	--clear)
		echo ":: Cleaning builddir..."
		echo "  $(du -hcs ~/.cache/buildaur/build | xargs | awk {'print $1'})B will be removed!"
		rm -rf ~/.cache/buildaur/build/*
		echo ":: Done!"
		exit 0
	;;
	--listhooks)
		listhooks
		exit 0
	;;
	--hook-activate)
		shift
		if [[ $1 = all ]]
		then
			activate $(ls /etc/buildaur/hooks)
		else
			activate $@
		fi
		exit 0
	;;
	--hook-deactivate)
		shift
		if [[ $1 = all ]]
		then
			deactivate $(ls /etc/buildaur/prehooks) $(ls /etc/buildaur/posthooks)
		else
			deactivate $@
		fi
		exit 0
	;;
	--help-hooks)
		hookhelp
		exit 0
	;;
	--make-chroot)
		echo ":: Creating a chrootdir"
		sudo rm -rf ~/chroot 2>/dev/null
		mkdir ~/chroot
		export CHROOT=$HOME/chroot
		mkarchroot $CHROOT/root base-devel
		echo "export CHROOT=$HOME/chroot" >> $HOME/.bashrc
		exit 0
	;;
	*)
		if [[ $1 = "" ]]
		then
			echo ":: ${red}${bold}ERROR:${normal} No options are given! Try --help to see all options!"
			exit 2
		else
			# give an error if the option in unknown
			echo ":: ${red}${bold}ERROR:${normal} '$@' is no known option! Try --help to see all options!"
			exit 2
		fi
	;;
esac
