#!/usr/bin/env bash
type=pre
desc="Fixes architecture issues for alarm. This may cause trouble with binary packages for x86_64 wich will then be installed as arm ones!"

if [[ $1 = "-u" ]]
then
  . ./PKGBUILD
  if [[ $(uname -m) = armhf ]] && [[ $arch = x86_64 ]]
  then
    echo Warning arch is $arch
  fi
echo "arch=(any)" >> ./PKGBUILD
fi
