#!/usr/bin/env bash
type=pre
desc="Fixes architecture issues for alarm. This may cause trouble with binary packages for x86_64 wich will then be installed as arm ones!"

if [[ $1 = "-u" ]]
then
  . ./PKGBUILD
  counter=0
  archerrorcount=0
  for i in ${#arch[*]}
  do
    if [[ $(uname -m) != ${arch[$counter]} ]] && [[ ${arch[$counter]} != any ]]
    then
      ((archerrorcount++))
    fi
    ((counter++))
  done
  if [[ $archerrorcount = ${#arch[*]} ]]
  then
    echo "Warning: architecture is ${arch[@]}"
  fi
  echo "arch=(any)" >> ./PKGBUILD
fi
