#!/usr/bin/env bash
bold=$(tput bold)
red=$(tput setaf 1)
normal=$(tput sgr0)
type=pre
desc="Fixes architecture issues for alarm. This may cause trouble with binary packages for x86_64 wich will then be installed as arm ones!"

if [[ $1 = "-u" ]]
then
  . ./PKGBUILD
  counter=0
  archerrorcount=0
  for i in "${arch[@]}"
  do
    if [[ $(uname -m) != ${arch[$counter]} ]] && [[ $arch != any ]]
    then
      ((archerrorcount++))
    fi
    ((counter++))
  done
  if [[ $archerrorcount = ${#arch[*]} ]]
  then
    echo "${bold}Warning:${normal} architecture is ${arch[@]}"
  fi
  echo -e "\n arch=(any)" >> ./PKGBUILD
fi
