#!/usr/bin/env bash
type=pre
desc="optimises make for faster compiling"

if [[ $1 = "-u" ]]
then
echo 'make(){' >> ./PKGBUILD
echo '/usr/bin/make -j $(nproc) "$@"' >> ./PKGBUILD
echo '}' >> ./PKGBUILD
echo "" >> ./PKGBUILD
echo 'ninja(){' >> ./PKGBUILD
echo '/usr/bin/ninja -j $(nproc) "$@"' >> ./PKGBUILD
echo '}' >> ./PKGBUILD
fi
